version: '3'
services:
  azure-vote-back:
    image: redis
    container_name: redis_server
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  azure-vote-front:
    image: vote:v1
    container_name: vote
    environment:
      REDIS: redis_server
    ports:
        - "80:5000"
